
#################################################
### THIS FILE WAS AUTOGENERATED! DO NOT EDIT! ###
#################################################
# file to edit: nb/function.ipynb
from math import ceil

def ceil_power_of_two(x):
    x = ceil(x) - 1
    res = 0
    while x > 0:
        x = x // 2
        res = res + 1

    return 2**(res)